networks:
  backend:
  frontend:

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.marqueeresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.marqueeresolver.acme.email=juliajsson@hotmail.com"
      - "--certificatesresolvers.marqueeresolver.acme.storage=/encrypt/acme.json"
    ports:
      # The HTTP port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - encrypt:/encrypt
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    depends_on:
      api-inventory:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile.Development
    restart: always
    ports:
      - "3000:3000"
    command: "npm run dev"
    volumes:
      - ./frontend/src:/app/src:readonly
    environment:
      - CHOKIDAR_POLLING=true
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host('frankenbunny.com')"
      - "traefik.hhtp.routers.frontend.entryPoints=websecure"
      - "traefik.http.routers.frontend.tls.certificateresolvers=marqueeresolver"

  api-inventory:
    build:
      context: ./backend/
      dockerfile: Dockerfile.Development
    ports:
      - "8090:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    volumes:
      - ./backend/inventory:/api/inventory/src:readonly
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=${POST_HOST}
      - DB_NAME=${POST_NAME}
      - DB_USER=${POST_USER}
      - DB_PASSWORD=${POST_PASSWORD}
    networks:
      - backend
      - frontend

  postgres:
    container_name: ${POST_HOST}
    image: postgres:latest
    restart: always
    depends_on:
      reverse-proxy:
        condition: service_started
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POST_USER}
      POSTGRES_PASSWORD: ${POST_PASSWORD}
      POSTGRES_DB: ${POST_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-q", "-d", "${POST_NAME}", "-U", "${POST_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

volumes:
  pgdata:
  encrypt:
