networks:
  backend:
  frontend:

services:
#  web:
#    build:
#      context: ./marquee-frontend
#      dockerfile: Dockerfile.Development
#    #environment:
#    #  NODE_ENV: Development
#    #  API_URL: "http://api:8080"
#    depends_on:
#      - api
#    ports:
#      - "5173:5173"
#    networks:
#     - frontend

  api:
    build:
      context: ./marquee-server/
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=${POST_HOST}
      - DB_NAME=${POST_NAME}
      - DB_USER=${POST_USER}
      - DB_PASSWORD=${POST_PASSWORD}
    networks:
      - backend
      - frontend

  postgres:
    container_name: ${POST_HOST}
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POST_USER}
      POSTGRES_PASSWORD: ${POST_PASSWORD}
      POSTGRES_DB: ${POST_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POST_NAME}", "-U", "${POST_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend
  
volumes:
  pgdata: