services:
  api:
    build:
      context: ./marquee-server/
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      ms-sql-server:
        condition: service_healthy
      #  condition: service_healthy
      #  restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=marquee-database
      - DB_NAME=marquee-database
      - DB_PASSWORD=FrankenBunnyDevelops<1Databases
#      - ASPNETCORE_HTTP_PORTS=80;8080
#      - ASPNETCORE_HTTPS_PORTS=443;8081
#      - ASPNETCORE_URLS=http://*:80/;http://*:8080/;https://*:443/;https://*:8081/
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
#    volumes:
#      - ~/.aspnet/https:/https:ro

  ms-sql-server:
    container_name: marquee-database
    hostname: marquee-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "FrankenBunnyDevelops<1Databases"
      MSSQL_TCP_PORT: 1433
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "http://localhost:1433", "-U", "sa", "-P", "FrankenBunnyDevelops<1Databases", "-Q", "SELECT 1", "||", "exit 1"]