networks:
  backend:
  frontend:

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80" # Define HTTP entry point
      - "--entrypoints.websecure.address=:443" # Define HTTPS entry point
    #  - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # Optional for automatic HTTPS with Let's Encrypt (adjust for production)
    #  - "--certificatesresolvers.myresolver.acme.email=youremail@example.com" # Required if using Let's Encrypt
    #  - "--certificatesresolvers.myresolver.acme.storage=/encrypt/acme.json"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # The HTTPS port
      - "443:443"
    volumes:
      - encrypt:/encrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend

  frontend:
    depends_on:
      api-inventory:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile.Development
    restart: always
    command: "npm run dev"
    volumes:
      - ./frontend/src:/app/src:readonly
    environment:
      - CHOKIDAR_POLLING=true
    ports:
      - "3000:3000"
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frankenbunny.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.api-inventory.entrypoints=web"

  api-inventory:
    build:
      context: ./backend/
      dockerfile: Dockerfile.Development
    ports:
      - "8090:8081"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    volumes:
      - ./backend/inventory:/api/inventory/src:readonly
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=${POST_HOST}
      - DB_NAME=${POST_NAME}
      - DB_USER=${POST_USER}
      - DB_PASSWORD=${POST_PASSWORD}
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-inventory.rule=Host(`frankenbunny.com`)"
      - "traefik.http.services.api-inventory.loadbalancer.server.port=8081"
      - "traefik.http.routers.api-inventory.entrypoints=web"

  postgres:
    container_name: ${POST_HOST}
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POST_USER}
      POSTGRES_PASSWORD: ${POST_PASSWORD}
      POSTGRES_DB: ${POST_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-q", "-d", "${POST_NAME}", "-U", "${POST_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

volumes:
  pgdata:
  encrypt:
